import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      // Development's empty dev-dist directory has nothing to precache. The
      // production service worker is still generated by the normal build.
      devOptions: { enabled: false },
      includeAssets: [
        'fieldsync-mark.svg',
        'icons/fieldsync-192.png',
        'icons/fieldsync-512.png',
      ],
      manifest: {
        name: 'FieldSync',
        short_name: 'FieldSync',
        id: '/',
        scope: '/',
        description: 'Offline-first field care for rural communities',
        theme_color: '#245c46',
        background_color: '#f5f7f2',
        display: 'standalone',
        start_url: '/',
        icons: [
          {
            src: '/icons/fieldsync-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: '/icons/fieldsync-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any maskable',
          },
          {
            src: '/fieldsync-mark.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'any',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,svg,webmanifest,webp,avif,woff,woff2}'],
        navigateFallback: '/index.html',
        navigateFallbackDenylist: [/^\/api(?:\/|$)/],
        cleanupOutdatedCaches: true,
        clientsClaim: true,
      },
    }),
  ],
})
