import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      // Development's empty dev-dist directory has nothing to precache. The
      // production service worker is still generated by the normal build.
      devOptions: { enabled: false },
      includeAssets: ['fieldsync-mark.svg'],
      manifest: {
        name: 'FieldSync',
        short_name: 'FieldSync',
        description: 'Offline-first rural telemedicine',
        theme_color: '#245c46',
        background_color: '#f5f7f2',
        display: 'standalone',
        start_url: '/',
        icons: [
          {
            src: '/fieldsync-mark.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'any maskable',
          },
        ],
      },
    }),
  ],
})
